/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Layer2__factory } from "./Layer2__factory";
export { Layer2Scaling__factory } from "./Layer2Scaling__factory";
