/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Layer2 } from "./Layer2";
export type { Layer2Scaling } from "./Layer2Scaling";
export * as factories from "./factories";
export { Layer2__factory } from "./factories/Layer2__factory";
export { Layer2Scaling__factory } from "./factories/Layer2Scaling__factory";
